### ISSUE TITLE
ERR_CONTENT_DECODING_FAILED on windows xampp

### ISSUE THREAD

**Issue by philastrophist** [d8ahazard/Phlex#137]
I `git clone` the repository and start apache in xampp. Navigating to `http://localhost/phlex/` gives `ERR_CONTENT_DECODING_FAILED`

No content loaded. For comparison, xampp's dashboard loads perfectly.

Windows 10

**Comment by philastrophist** [comment]
Fixed: gzip needs to be disabled in `php.ini`

`zlib.output_compression= Off`

**Comment by sbozzie** [comment]
In my php.ini (opened via the XAMPP control panel) this option is marked as:

    zlib.output_compression= Off

I'm still having this issue.

**Comment by philastrophist** [comment]
Mmm. My full addition is:

```
zlib.output_compression= Off
display_errors = Off
error_reporting = E_ALL & ~E_STRICT
```

I don't see how that would help though (this was a copy paste)

**Comment by sbozzie** [comment]
Copy-pasting that section in still results in the same error.

Just for sanity: I'm currently making these changes using XAMPP control Panel V3.2.2
I'm clicking the "config" button by Apache, and choosing "PHP (php.ini)" which opens the config file in notepad.

Is there somewhere else I need to make a settings change perhaps?

**Comment by sbozzie** [comment]
Out of curiosity/tinkering, I set output_compression to "On" and the initial page loaded but with the following errors:


    Notice: Undefined index: general in C:\xampp\htdocs\phlex\vendor\pear-
    pear.php.net\Config_Lite\Config\Lite.php on line 468

    Warning: array_key_exists() expects parameter 2 to be array, null given in 
    C:\xampp\htdocs\phlex\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php on line 468
    
    Warning: ob_start(): output handler 'ob_gzhandler' conflicts with 'zlib output compression' in 
    C:\xampp\htdocs\phlex\index.php on line 16
    
    Notice: ob_start(): failed to create buffer in C:\xampp\htdocs\phlex\index.php on line 16

**Comment by philastrophist** [comment]
I had those as well if I turned it on.

**Comment by sbozzie** [comment]
I have no real idea what I'm doing but:

I changed line 16 of index.php to:

    if (substr_count($_SERVER["HTTP_ACCEPT_ENCODING"], "gzip")) ob_start();

I'm in, and the errors have gone away - not sure if it's actually working or not yet! :p

**Comment by d8ahazard** [comment]
Yeah, apparently, I need a check to make sure gzip output is available on the server.  

Just added a check that *should* resolve the issue, at least it works clean on Xampp.
