### ISSUE TITLE
New install - unable to login to Phlex welcome screen 

### ISSUE THREAD

**Issue by tattsjc** [d8ahazard/Phlex#182]
When I try and login to the phlex welcome screen I just get invalid password 

This is my phlex log 

[Sat, 04 Nov 2017 14:54:16 +0000] [DEBUG] [api.php] - Session Started
[Sat, 04 Nov 2017 14:54:16 +0000] [INFO] [api.php::checkSignIn] - Trying to sign into Plex.tv as Toxictatts.
[Sat, 04 Nov 2017 14:54:16 +0000] [DEBUG] [util.php::signIn] - No token or not signed in, signing into Plex.
This is my httpd log 
[Sat Nov 04 14:39:53.491927 2017] [suexec:notice] [pid 3039] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Sat Nov 04 14:39:53.510523 2017] [auth_digest:notice] [pid 3039] AH01757: generating secret for digest authentication ...
[Sat Nov 04 14:39:53.510922 2017] [lbmethod_heartbeat:notice] [pid 3039] AH02282: No slotmem from mod_heartmonitor
[Sat Nov 04 14:39:53.589486 2017] [mpm_prefork:notice] [pid 3039] AH00163: Apache/2.4.6 (CentOS) PHP/7.0.24 mod_perl/2.0.9dev Perl/v5.16.3 configured -- resuming normal operations
[Sat Nov 04 14:39:53.589506 2017] [core:notice] [pid 3039] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

Any idea how to proceed?

**Comment by d8ahazard** [comment]
I'd try pulling the updates I just pushed out, see if that helps...

**Comment by tattsjc** [comment]
Have that go and still no luck 

[Fri, 10 Nov 2017 16:57:49 +0000] [DEBUG] [api.php] - INCOMING REQUEST!!
[Fri, 10 Nov 2017 16:57:49 +0000] [DEBUG] [api.php] - LOGIN TRIGGERED
[Fri, 10 Nov 2017 16:57:49 +0000] [INFO] [api.php::checkSignIn] - Trying to sign into Plex.tv as tattersall@gmail.com.
[Fri, 10 Nov 2017 16:57:49 +0000] [DEBUG] [util.php::signIn] - No token or not signed in, signing into Plex.
[Fri, 10 Nov 2017 16:57:50 +0000] [DEBUG] [api.php] - Sorry, couldn't validate user.
[Fri, 10 Nov 2017 16:57:50 +0000] [ERROR] [api.php] - ERROR: Unauthenticated access detected.  Originating IP - 192.168.0.2
[Fri, 10 Nov 2017 16:57:50 +0000] [DEBUG] [api.php] - Post BODY: username=tattersall%40gmail.com&password=******
[Fri, 10 Nov 2017 16:57:50 +0000] [DEBUG] [api.php] - Invalid API Token, forcing logout.
[ty@Izzy ~]$

**Comment by tattsjc** [comment]
I've changed my user and pass for secuirtyy

**Comment by d8ahazard** [comment]
Anything in the phlex_error.log or java console when you press F12 in a
browser?
