### ISSUE TITLE
warning message after updating the latest version

### ISSUE THREAD

**Issue by phairplay** [d8ahazard/Phlex#256]
hi,
ive update phlex to the latest version and im seeing the below error when i log in.

`Warning: fopen(C:\xampp\htdocs\Phlex\logs\Phlex.log.php): failed to open stream: Permission denied in C:\xampp\htdocs\Phlex\util.php on line 441
`

also google response with “phlex tv isnt responding right now” yet it still completes my action requests.

how can i resolve this?

**Comment by parlarkin** [comment]
I fixed the error code by adding a blank document named Phlex.log.php to phlex>logs folder

**Comment by phairplay** [comment]
Thanks I tried that but it didn’t work. Still getting the same issue

**Comment by Antimus** [comment]
It's a problem with one of the commits from the 15th, I've reverted to the commit from the 14th and it's working

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
