### ISSUE TITLE
Movies/TV play on my Roku TV through Google Home, but trying to play music causes the Roku to just exit Plex

### ISSUE THREAD

**Issue by SamLewis0602** [d8ahazard/Phlex#283]
## ISSUE TEMPLATE

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 1. On what OS are you running Phlex?
Ubuntu Linux

#### 2. Are you using a new instance of XAMPP, or an existing webserver?
New instance of xampp

#### 2b. If not XAMPP, what WebServer stack are you using?
N/A

#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
No

#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes

#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.
My issue is that Phlex works beautifully when playing a movie or a TV show on my Roku TV, even through my Google Home. However, whenever I try to play music, the Roku just exits the Plex app. Below are the log lines from an entire interaction requesting to "play a day to remember". The same behavior happens with all music requests.
```
788[Fri, 29 Dec 2017 16:38:33 +0100] [INFO] [api.php::parseApiCommand] - Final params should be an action of play, a command of day to remember, a type of , and a control of . 
789[Fri, 29 Dec 2017 16:38:33 +0100] [INFO] [api.php::parseApiCommand] - Final media result: false 
790[Fri, 29 Dec 2017 16:38:33 +0100] [INFO] [api.php::plexSearch] - URL is https://192-168-1-161.c07750b6d1474a1d9bfadb18d1dfb1a5.plex.direct:32400/hubs/search?query=day+to+remember&limit=30&X-Plex-Token=XXXXXXXXXX
791[Fri, 29 Dec 2017 16:38:33 +0100] [INFO] [api.php::fetchMediaExtra] - URL is https://192-168-1-161.c07750b6d1474a1d9bfadb18d1dfb1a5.plex.direct:32400/library/metadata/1826?X-Plex-Token=XXXXXXXXXX
792[Fri, 29 Dec 2017 16:38:34 +0100] [INFO] [api.php::fetchMediaExtra] - URL is https://192-168-1-161.c07750b6d1474a1d9bfadb18d1dfb1a5.plex.direct:32400/library/metadata/1826?X-Plex-Token=XXXXXXXXXX
793[Fri, 29 Dec 2017 16:38:34 +0100] [INFO] [api.php::plexSearch] - Return array: [JSON]
794[Fri, 29 Dec 2017 16:38:34 +0100] [INFO] [api.php::queueMedia] - URL is https://192-168-1-161.c07750b6d1474a1d9bfadb18d1dfb1a5.plex.direct:32400/library/metadata/1826?X-Plex-Token=XXXXXXXXXX
795[Fri, 29 Dec 2017 16:38:34 +0100] [INFO] [api.php::queueMedia] - URL is https://192-168-1-161.c07750b6d1474a1d9bfadb18d1dfb1a5.plex.direct:32400/playQueues?type=audio&uri=library://cd7d9a4b-0b32-41d2-bb57-d211d857d9c5/item/%2Flibrary%2Fmetadata%2F1826&shuffle=0&repeat=0&includeChapters=1&own=1&X-Plex-Client-Identifier=d5b3d6e7375cf004c57f6665&X-Plex-Product=Phlex&X-Plex-Version=1.0.0&X-Plex-Platform=Web&X-Plex-Platform-Version=1.0.0&X-Plex-Device=PhlexWeb&X-Plex-Device-Name=Phlex&X-Plex-Device-Screen-Resolution=1520x707,1680x1050,1920x1080&X-Plex-Token=XXXXXXXXXX
796[Fri, 29 Dec 2017 16:38:34 +0100] [INFO] [api.php::returnSpeech] - My reply is going to be 'Sure, Playing A Day to Remember.'. 
797[Fri, 29 Dec 2017 16:38:34 +0100] [INFO] [api.php::queueMedia] - URL is https://192-168-1-161.c07750b6d1474a1d9bfadb18d1dfb1a5.plex.direct:32400/library/metadata/1826?X-Plex-Token=49E4WAP2k9yRqgBTZXoE
798[Fri, 29 Dec 2017 16:38:34 +0100] [DEBUG] [api.php] - INCOMING REQUEST!!
799[Fri, 29 Dec 2017 16:38:34 +0100] [DEBUG] [api.php] - Using token from GET
800[Fri, 29 Dec 2017 16:38:34 +0100] [INFO] [api.php::queueMedia] - URL is https://192-168-1-161.c07750b6d1474a1d9bfadb18d1dfb1a5.plex.direct:32400/playQueues?type=video&uri=library://cd7d9a4b-0b32-41d2-bb57-d211d857d9c5/item/%2Flibrary%2Fmetadata%2F1826&shuffle=0&repeat=0&includeChapters=1&own=1&X-Plex-Client-Identifier=d5b3d6e7375cf004c57f6665&X-Plex-Product=Phlex&X-Plex-Version=1.0.0&X-Plex-Platform=Web&X-Plex-Platform-Version=1.0.0&X-Plex-Device=PhlexWeb&X-Plex-Device-Name=Phlex&X-Plex-Device-Screen-Resolution=1520x707,1680x1050,1920x1080&X-Plex-Token=XXXXXXXX 
801[Fri, 29 Dec 2017 16:38:34 +0100] [ERROR] [util.php::curlGet] - Unexpected HTTP code: 500, URL: https://192-168-1-161.c07750b6d1474a1d9bfadb18d1dfb1a5.plex.direct:32400/player/playback/playMedia?key=%2Flibrary%2Fmetadata%2F1826&offset=0&machineIdentifier=fefacb44c2b59899f23b7f9035cee29b48c07315&protocol=https&address=192-168-1-161.c07750b6d1474a1d9bfadb18d1dfb1a5.plex.direct&port=32400&containerKey=%2FplayQueues%2F167%3Fown%3D1%26window%3D200&token=transient-155e0929-4418-479b-9128-c6ac8e73ba6a&commandID=16
```
#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
fea719

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle

**Comment by SamLewis0602** [comment]
I gave the beta branch a try, and did some extensive testing but found that the Roku TV Plex app still crashes when I try to play music and it's now crashing for Movies/TV as well. I found a line in the Phlex.log.php file that was complaining about getting a 500 back from the URL used to actually issue the play command. I copied the URL found in the logs and pasted it into a browser and received the following XML error back with a stack trace in it. I can launch Plex on my RokuTV, refresh the page to send the command again, and it crashes the Plex app on my TV every time. Here is the XML response:
```
<Response code="2000" status="BadStatusLine: "><Traceback>Traceback (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
    result = f(**d)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/System.bundle/Contents/Code/playerservice.py", line 38, in process_remote_command
    headers=Request.Headers)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 194, in Request
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1217, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1190, in do_open
    r = h.getresponse()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/httplib_new.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/httplib_new.py", line 431, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/httplib_new.py", line 395, in _read_status
    raise BadStatusLine(line)
BadStatusLine
</Traceback></Response>
```
I'm not familiar with the code behind Plex (or Phlex for that matter) so I'm not sure if this will help point you in the right direction, but I'm hoping it can. Let me know if I can get you any more useful information since I can reproduce the issue.

**Comment by ch491** [comment]
Did you solve this problem? I am new to Phlex and just installed and have the same problem with my Roku/Plex client. Can pause but that is about it from Google --> Phlex --> Plex

**Comment by SamLewis0602** [comment]
Unfortunately not, I gave up on it long ago.

**Comment by ch491** [comment]
That is sad to hear. I hope Plex hears our cry for a true Google Home Link  Thank you for the quick reply.
