### ISSUE TITLE
Feature Request: Plex Home User Recognition

### ISSUE THREAD

**Issue by klusion** [d8ahazard/Phlex#35]
Requesting Plex Home User Recognition

Within Plex > Settings > Users I have some users under "My Home". These users do not have an official Plex account but a login tied to mine. When you load the Plex app on Roku (or any other Plex app for that matter) you can select which user account you want to login to for tracking your watched content. When I select my account within Plex, the player is registered as available to control within Phlex, but if I select another user account within "My Home," the player is not recognized in the Phlex web ui.

**Comment by eddiezab** [comment]
I am not the one that opened this issue, but I was having a similar issue. It seems at some point in time, it has been resolved. I'm able to detect other Plex Media Players that are logged in as sub-accounts.

**Comment by d8ahazard** [comment]
Hey, that's awesome!  I'll go ahead and close this then.

**Comment by klusion** [comment]
Hello. I installed the latest version of the Phlex, but it still does not recognize when a Plex Home user is logged into one of the players. Any ideas?

**Comment by d8ahazard** [comment]
I believe the player needs to be pointed at the same server as Phlex for it
to find it.
