### ISSUE TITLE
Error 22

### ISSUE THREAD

**Issue by hitnrun30** [d8ahazard/Phlex#362]
### IMPORANT, PLEASE READ FIRST:

Due to an overwhelming amount of issues with cast devices and network issues in general, I've begun
a complete overhaul of the codebase behind Flex TV. This includes delgating cast functionality to a custom
Plex Media Server plugin (https://github.com/d8ahazard/Cast.bundle), as well as a major reworking of device
scraping and storage, fetcher interactions, UI overhauls, and basically - rewriting a massive chunk of
the application.

Pending the release of Flex TV v2, I ask that you refrain from submitting issues regarding...well...most of the things.

Casting, device fetching, data storage, signin issues, media fetcher interactions, multiple languages...all
of these are receiving major love...and so until then, just sit tight.

I am still looking for OS-related issues (FreeBSD causes problems), and issues related to one-off players, smart TV's,
things that aren't related to casting or server connectivity. Also, feature requests.

That said - we now return you to your regularly scheduled program.

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

#### 1. On what OS are you running Flex TV?
Windows 10
#### 2b. If not XAMPP, what WebServer stack are you using?
nginx
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
Yes
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Flex TV)
bd1b11

I keep getting an Error 22: The requested URL returned error: 500 Internal Server Error

**Comment by d8ahazard** [comment]
Fixed.

**Comment by hitnrun30** [comment]
No it isn't, I am still getting a php warning in nginx

2018/06/25 13:10:17 [error] 10720#11124: *340066 FastCGI sent in stderr: "PHP Warning:  Erroneous data format for unserializing 'digitalhigh\JsonConfig' in C:\HTPC\nginx\html\Phlex\api.php on line 29
PHP Warning:  session_start(): Failed to decode session object. Session has been destroyed in C:\HTPC\nginx\html\Phlex\api.php on line 29" while reading response header from upstream, client: 173.161.144.145, server: strausshtpc.ddns.net, request: "GET /phlex/api.php?pollPlayer&apiToken=c0a173eae0f269aa4a3da3130fdab64c690fbd1b11&logLimit=50 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxxx.net", referrer: "https://xxxx.net/phlex/index.php"

**Comment by giejay** [comment]
Im having the same issue, logging in the first time works, but soon after that, the page is showing a spinner and is not loading anymore. Google Home reports: Error 22, internal server error, just like the browser shows for index.php
