### ISSUE TITLE
Google linking issue

### ISSUE THREAD

**Issue by jellevdbos** [d8ahazard/Phlex#364]
When I click on the "link google" button, a page starts loading and after a while i get the following message:

Unable to connect to Client at 
        <a href=myipadress>myipadress</a> or <a href='myipadress'>myipadress.</a><BR> Please check the setting for 'Public Address' in the Phlex UI.{"speech":"Unable to look up user.","contextOut":[{"name":"playmedia","lifespan":2,"parameters":[]}],"data":{"google":{"expectUserResponse":false,"isSsml":false,"noInputPrompts":[],"richResponse":{"items":[{"simpleResponse":{"textToSpeech":"Unable to look up user.","displayText":"Unable to look up user."}}]}}}}

Port forwarding is enabled and works
php is the latest version

I really have no clue what to do. Since i live in Belgium, i also cant install flex directly on my google home to try and link it there

1. On what OS are you running Flex TV?
Ubuntu server 16.04
2. Are you using a new instance of XAMPP, or an existing webserver?
new instance
2b. If not XAMPP, what WebServer stack are you using?

3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
yes
4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
yes, setup my router and i can reach flex from outside of my network

5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Flex TV and Flex TV_error.log files.  Paste anything that looks related as well.
Looked in the log files, no errors

6. What are the last six digits of your server's API Token? (Settings -> Flex TV)
7bf431

**Comment by jellevdbos** [comment]
![screenshot_20180617-234948](https://user-images.githubusercontent.com/40343959/41512531-047bc718-728a-11e8-8177-fcc56b54c589.jpg)

**Comment by Mdleal** [comment]
Same issue as me yesterday.  Glad it wasn't just me.

**Comment by automatt1c** [comment]
Im having the same issue as well. Was working great for me. my external DNS names changed but now it wont let me link the account even though i can access PhlexTV from my phone think i first tried it  Friday night. is there any tyoe of workaround we can do?

**Comment by charlie2alpha** [comment]
Add me to the list, I get an error claiming it can't connect to my Phlex but external connections work fine, I can connect from my work and my cell phone to my web server.

**Comment by TomasJAnderson** [comment]
Dear lord, add me to the list, I've turned this around every which way. Port forwarding, reverse proxy, creating a new subdomain, putting it in a folder, nothing gives.

Personally I'm using nginx as reverse proxy and the Flex docker as base.

**Comment by d8ahazard** [comment]
Fixed. Tried to be clever and add some security via IPTables, had a DROP ALL rule in place that was supposed to be deleted, but stuck around anyway. It's since been removed.

**Comment by automatt1c** [comment]
So I'm still having issues with linking the google account through the UI. 
Oddly enough you did fix something since now reverse linking it through the google home app seemed to work.  I haven't fully tested functionality though.

**Comment by jellevdbos** [comment]
I am still having issues as well. In the Google Home app it redirects to plexchat.com, but i only get a white tab. When i try to talk to phlex afterwards, it still says my google account isn't linked
