### ISSUE TITLE
Help Setting up Phlex (Seeing white screen at 'localhost/Phlex')

### ISSUE THREAD

**Issue by aMikeToThePast** [d8ahazard/Phlex#441]
Hi, I'm trying to set up Phlex on my raspberry pi.
I've followed the wiki https://github.com/d8ahazard/Phlex/wiki/Using-Raspberry-Pi
I've gotten down to editing php.ini and then restarted the apache2 server.
I type 'localhost/Phlex' into my web browser (locally on the raspberry pi) but all I get is a blank white screen.

What am I doing wrong? 
Should I not be seeing the instance of Phlex being hosted by my raspberry pi at this point?

**Comment by aMikeToThePast** [comment]
Checked the apache error logs and it seems like I'm having the same problem as that is issue 440 (https://github.com/d8ahazard/Phlex/issues/440)

I'm getting the same fatal error: 
PHP Fatal error:  Uncaught Error: Call to a member function get() on boolean in /var/www/html/Phlex/php/webApp.php:108\nStack trace:\n#0 /var/www/html/Phlex/php/webApp.php(446): getPreference('general', 'value', 'http://localhos...', 'name', 'publicAddress')\n#1 /var/www/html/Phlex/php/webApp.php(12): serverAddress()\n#2 /var/www/html/Phlex/index.php(3): require_once('/var/www/html/P...')\n#3 {main}\n  thrown in /var/www/html/Phlex/php/webApp.php on line 108

**Comment by d8ahazard** [comment]
This issue should be fixed with the latest commits.

**Comment by qwert9401** [comment]
That issue is solved but for me the loader is spinning all the time after allowing Phlex to access my Plex account (no errors in console and nothing in xampp logs as well). The same happens on instance hosted by you. What could be the issue?

**Comment by Dave-Still** [comment]
Saw a similar issue when trying to resolve the original issue myself. Symptoms were :-    in Phlex\logs\Phlex.log.php msg
[ERROR] [index::checkDefaults:setPreference:initConfig:__construct:__construct] - Error, dying to protect config.

If this is the case - 3 suggestions for resolution:-
1.) As this suggests a config issue, a straight reinstall of current Phlex version may fix by creating a new user if the current config is corrupted.
2.) As a temporary fix prior to this patch I copied the general, and userdata sections from a previous instance of Phlex\rw\config.php to a new file Phlex\rw\db in my current instance.
3.) In my current configuration I've moved to using MySQL to hold the config, but this has prove somewhat more complex than suggested in the guide. In my case creation of the 'userdata' table failed as the code (Phlex/php/webApp.php) set defaults on columns 'quietstart', and 'quietstop' that caused the create to fail:-

 `quietStart` tinytext NOT NULL DEFAULT '20:00',
 `quietStop` tinytext NOT NULL DEFAULT '8:00',

Removing the Default resolved this

 `quietStart` tinytext NOT NULL,
 `quietStop` tinytext NOT NULL,

Hopefully some food for thought

**Comment by dony71** [comment]
@Dave-Still I try your suggestion, but still doesn't work
It will ask again for login every time I reload phlex UI
Do you see "JSON Decode failed" also in your log like below?
cat Phlex.log.php >>>

[03-28-2019 00:45:49.118800] [ALERT] [index::] - -------NEW REQUEST RECEIVED-------
[03-28-2019 00:45:49.123300] [DEBUG] [index::checkDefaults] - Fetched defaults: {"deviceId":"49fb6ea2fcb57755db2246a6","forceSSL":false}
[03-28-2019 00:45:49.125000] [DEBUG] [index::] - ForceSSL is set to
[03-28-2019 00:45:49.130100] [DEBUG] [12345] [index::checkUpdate] - Function fired!
[03-28-2019 00:45:50.355900] [DEBUG] [12345] [index::checkUpdate:fetchCommits] - Command: 'git log 01fce92 -1 --pretty=format:"shortHead==%hD/Hhead==%HD/Hsubject==%sD/Hbody==%bD/Hauthor==%aND/H*date==%aD"'
[03-28-2019 00:45:50.382900] [ALERT] [12345] [index::require_once:require_once] - -------NEW REQUEST RECEIVED-------
[03-28-2019 00:45:50.389900] [DEBUG] [12345] [index::require_once:require_once:checkDefaults] - Fetched defaults: {"deviceId":"49fb6ea2fcb57755db2246a6","forceSSL":false}
[03-28-2019 00:45:50.397600] [DEBUG] [12345] [index::] - Making body!
[03-28-2019 00:45:50.415900] [DEBUG] [12345] [index::makeBody:makeSettingsBody:checkRevision] - Function fired!
[03-28-2019 00:45:50.518300] [INFO] [12345] [index::makeBody:makeSettingsBody:listLocales] - Local language should be en
[03-28-2019 00:45:50.634400] [ALERT] [12345] [index::makeBody:makeSettingsBody:fetchList:updateUserPreferenceArray:setPreference:initConfig:__construct:__construct:read] - JSON Decode failed!!
[03-28-2019 00:45:50.638700] [ERROR] [12345] [index::makeBody:makeSettingsBody:fetchList:updateUserPreferenceArray:setPreference:initConfig:__construct:__construct] - Error, dying to protect config.

**Comment by Dave-Still** [comment]
Hi Dony71. Yes, but the current issue is the Plex TV server is temporarlily down per the forum message:- 
https://forums.plex.tv/t/flex-tv-temporarily-down-for-updates/174627/2166

And currently unavailable in google per issue #444 

I don't believe Registration will be possible until this is resolved
