### ISSUE TITLE
Phlex sees null or undefined after starting playback

### ISSUE THREAD

**Issue by codymhorton** [d8ahazard/Phlex#85]
OS: Windows 10
New instance of XAMPP
Phlex is using Http
Casting to Chromecast Ultra

The issue I'm having is once I start playback (tried with both a movie and tv show) it starts fine but if you check it on the Phlex website it says null and undefined. I've attached a screenshot of this. Also when asking Phlex what is playing it says "the is playing" since there is no value there. Lastly the slider seems to be at a random spot could this be related to this same issue?

I've also attached a log file of me running all these commands (the server was just started and I grabbed the ones from that time)

Let me know if you need any other info. Thanks!

![capture](https://user-images.githubusercontent.com/6940180/27109230-70de7204-506f-11e7-964e-becef5324dcf.PNG)
[log.txt](https://github.com/d8ahazard/Phlex/files/1073146/log.txt)

**Comment by d8ahazard** [comment]
I am actively working on updating the status/check for Cast devices - this should be fixed today.

**Comment by codymhorton** [comment]
Ah okay I didn't realize this is a work in progress. I'll look for the update and close this if everything works well. Thanks!

**Comment by codymhorton** [comment]
I updated to the newest version but still no luck. If you haven't worked on this no rush but I just want to make sure I'm not doing something wrong. Thanks.

**Comment by d8ahazard** [comment]
This has been fixed with commit 0a20c475797e8fc5297b79ec678b3d7248d068e4

**Comment by codymhorton** [comment]
@d8ahazard Thanks! I can see the status now but strangely I can't advance or back track it in the web app. I bet it's due to the issue Plex is having with Chromecasts mentioned here: https://forums.plex.tv/discussion/265666/cant-resume-from-last-position/p3. Just wanted to give you a heads up. Thanks!
